# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Part.create(name: 'Engine')
Part.create(name: 'Engine Oil')
Part.create(name: 'Transmission')
Part.create(name: 'Transmission Oil')
Part.create(name: 'Brake pads')
Part.create(name: 'Tires')
Part.create(name: 'Oil filter')
Part.create(name: 'Air filter')
Part.create(name: 'Spark plugs')
Part.create(name: 'Radiator')
Part.create(name: 'Radiator Coolant')
Part.create(name: 'Battery')
Part.create(name: 'Alternator')
Part.create(name: 'Starter motor')
Part.create(name: 'Fuel pump')
Part.create(name: 'Ignition coil')
Part.create(name: 'Power steering pump')
Part.create(name: 'Water pump')
Part.create(name: 'Thermostat')
Part.create(name: 'Wheel bearings')
Part.create(name: 'Suspension struts')
Part.create(name: 'Shock absorbers')
Part.create(name: 'Control arms')
Part.create(name: 'Ball joints')
Part.create(name: 'Tie rods')
Part.create(name: 'CV joints')
Part.create(name: 'Drive belts')
Part.create(name: 'Timing belt')
Part.create(name: 'Timing chain')
Part.create(name: 'Catalytic converter')
Part.create(name: 'Exhaust manifold')
Part.create(name: 'Oxygen sensor')
Part.create(name: 'Mass air flow sensor')
Part.create(name: 'Throttle body')
Part.create(name: 'EGR valve')
Part.create(name: 'Camshaft position sensor')
Part.create(name: 'Crankshaft position sensor')
Part.create(name: 'Intake manifold gasket')
Part.create(name: 'Head gasket')
Part.create(name: 'Piston rings')
Part.create(name: 'Connecting rods')
Part.create(name: 'Cylinder head')
Part.create(name: 'Piston')
Part.create(name: 'Crankshaft')
Part.create(name: 'Camshaft')
Part.create(name: 'Flywheel')
Part.create(name: 'Clutch kit')
Part.create(name: 'Master cylinder')
Part.create(name: 'Slave cylinder')
Part.create(name: 'Brake master cylinder')
Part.create(name: 'Brake booster')
